[package]
authors = ["dnaq"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://dnaq.github.io/sodiumoxide"
keywords = ["crypto", "NaCl", "libsodium"]
license = "MIT"
name = "sodiumoxide"
readme = "README.md"
repository = "https://github.com/dnaq/sodiumoxide"
version = "0.0.8"

[dependencies]
libc = "0.2.1"
libsodium-sys = "*"
rustc-serialize = "0.3.16"

[features]
benchmarks = []
